### ISSUE TITLE
More on missing values Notebook issue

### ISSUE THREAD

**Issue by joshuarwanda** [learn-co-curriculum/dsc-more-on-missing-data#1]
## Link to Canvas

https://moringa.instructure.com/courses/243/assignments/21613?module_item_id=44685

## Issue Subtype

- [ x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [x] Linux
- [ ] Saturn Cloud from Canvas

## Any Additional Context?

Link to open notebook loads as untitled with no content.

**Comment by jessepisel** [comment]
Thanks for opening this issue with us :wave:. I have updated the Saturn Cloud link so that it directs to the correct notebook. It is functioning as intended at this time.
