### ISSUE TITLE
Saturn Cloud opening empty notebook

### ISSUE THREAD

**Issue by joeldmott** [learn-co-curriculum/dsc-more-on-missing-data#2]
## Link to Canvas

https://learning.flatironschool.com/courses/6534/assignments/240617?module_item_id=565608

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

## Describe the Issue
Clicking the Saturn Cloud link to the lesson takes me to an empty notebook. It worked when I changed the end of the url from "Untitled.ipynb" to  "index.ipynb".

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
Thanks for opening this issue :wave:. The link has been updated on the Canvas page for this lesson and opens the correct Saturn Cloud notebook.
