### ISSUE TITLE
Lesson Opening Empty Notebook

### ISSUE THREAD

**Issue by KarimiNyaga** [learn-co-curriculum/dsc-more-on-missing-data#3]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
Thanks for opening this issue :wave:. Can you provide a link to the Canvas url for this lesson?

**Comment by bpurdy-ds** [comment]
Since the link was not given, I'm going to close. Please reopen if need be with the link.
