### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by JoanWambua** [learn-co-curriculum/dsc-more-on-missing-data#4]
## Link to Canvas

https://w-joanw-ds-course-phase1-2e94a332367f437788fbbee7dbace74e.moringa.saturnenterprise.io/notebooks/workspace/flatiron-curriculum/Phase1/dsc-more-on-missing-data/Untitled.ipynb

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x ] Other (explain below)

## Describe the Issue
I am unable to locate the lesson from this page. It says 404 : Not Found
You are requesting a page that does not exist!
### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [x ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Hello. Thanks for raising this issue and given us the SaturnCloud link.
May you also give the Canvas link, i.e. the page that has the SaturnCloud link.
Thank you.

**Comment by JoanWambua** [comment]
Evening.

Here is the link.
https://moringa.instructure.com/courses/514/assignments/35729?module_item_id=75256

Regards.

**Comment by bpurdy-ds** [comment]
Fixed. Let us know if there are any other issues, and thanks again for bringing this to our attention.
